### PR TITLE
Delete `provenance` and `run` related code.

### PR DESCRIPTION
**Pull request by rohinb2**
with no regards to BC :).

### CODE REVIEW

**Comment by rohinb2** [comment]
* **#1221** <a href="https://app.graphite.dev/github/pr/run-house/runhouse/1221?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rohinb2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by jlewitt1** [comment]
there are also some reference to `provenance` in the config printed in the tutorial docs (`api-resources.rst`), maybe we just remove those fields?

**Review by BelSasha — APPROVED** [review]
looks good

**Comment by rohinb2** [comment]
### Merge activity

* **Sep 3, 2:01 PM EDT**: @rohinb2 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/run-house/runhouse/1221).

**Pull request merged**
