### PR TITLE
Move `_generate_default_name` into general utilities.

### PR DESCRIPTION
**Pull request by rohinb2**
Since this doesn't rely on any Runhouse utilities, we can move it to the generic utils file and use it more easily.

### CODE REVIEW

**Comment by rohinb2** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/run-house/runhouse/1140?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1140** <a href="https://app.graphite.dev/github/pr/run-house/runhouse/1140?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#1138** <a href="https://app.graphite.dev/github/pr/run-house/runhouse/1138?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1137** <a href="https://app.graphite.dev/github/pr/run-house/runhouse/1137?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rohinb2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by carolineechen — APPROVED** [review]
changes look fine but what was the reason to move it out / make it a public function? should we move the remaining function in utils/names.py out too?

**Comment by rohinb2** [comment]
> changes look fine but what was the reason to move it out / make it a public function? should we move the remaining function in utils/names.py out too?

@carolineechen I'll be using this in an upcoming PR. In general, if a function (or any set of code) only relies on fundamental libraries and no other Runhouse code, putting it in the base utils file helps prevent circular imports and make it easier to access. 

The other function in names.py is not as simple and needs some RNS stuff, so I left it.

**Comment by rohinb2** [comment]
### Merge activity

* **Aug 16, 4:58 PM EDT**: @rohinb2 started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/run-house/runhouse/1140).

**Pull request merged**
