### PR TITLE
updated tokens for dev ci testing

### PR DESCRIPTION
**Pull request by jlewitt1**
Update env vars for the various den accounts used in testing

### CODE REVIEW

**Comment by jlewitt1** [comment]
* **#1236** <a href="https://app.graphite.dev/github/pr/run-house/runhouse/1236?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @jlewitt1 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by mkandler — APPROVED** [review]
So much more clear!! Is this renaming going to break anything without changing the references to the env vars too?

**Comment by jlewitt1** [comment]
actually that's a good point, would we be able to reuse the same tokens for dev/prod? otherwise we would need to branch in the test code a bit to know which env var to load

**Comment by mkandler** [comment]
I think we'll need different tokens for dev and production since they'll be generated by a different private/public key pair on Den dev v Dev Prod (those should definitely not be the same)

**Pull request merged**
