### PR TITLE
Prevent RecursionError in import (for Windows, path dependent)

### PR DESCRIPTION
**Pull request by aria1th**
in Windows, if Python path is `C:\\Python`, then it can throw RecursionError on startup.

### CODE REVIEW

**Comment by dongreenberg** [comment]
Great catch!! Thank you for adding it. Out of curiosity, did you run into any other issue on Windows or was this it?

**Comment by aria1th** [comment]
@dongreenberg in runhouse side - this is the only error I catched, but in skypilot - I had some more issues with it 😭

**Comment by dongreenberg** [comment]
@aria1th were they the same as https://github.com/run-house/runhouse/issues/58?

**Comment by aria1th** [comment]
@dongreenberg Yes, that problem is solved by [pr in skypilot side](https://github.com/skypilot-org/skypilot/pull/1955). Its also in [issue ](https://github.com/skypilot-org/skypilot/issues/1950)
So runhouse does not have responsibility about that problem, but still some problem remains, such as not creating directory before executing rsync, etc. Well manually executing commands could solve but debugging was hard... so it might require separate logger for windows environment...

**Pull request merged**
